version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pharmastream_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pharma
      POSTGRES_PASSWORD: pharma123
      POSTGRES_DB: pharmastream
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pharmastream_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
